### ISSUE TITLE
Not working with instagram?

### ISSUE THREAD

**Issue by timfoulkes** [ericf1/ftwbot#5]
Whenever I try to add an instagram account, I get a message saying "User [name] does not exist on Instagram"

**Comment by delasource** [comment]
other user report the same problems. https://stackoverflow.com/questions/72467565/error-when-scraping-instagram-media-by-adding-at-the-end-of-url-a-1

i think it is some cookie bs. If i open a url like `https://www.instagram.com/ANY_USERNAME/feed/?__a=1` in the browser it does not work when i'm logged in, but in an incognito tab it works. 

```
for (;;);{"__ar":1,"error":1357004,"errorSummary":"Leider ist etwas schiefgelaufen.","errorDescription":"Bitte versuche, diese Seite neu zu laden oder schlie\u00dfe dein Browserfenster und \u00f6ffne es erneut.","payload":null,"hsrp":{"hblp":{"consistency":{"rev":1005620047}}},"lid":"7104581948718936788"}
```
(strangely there is a 'for' at the beginning of the json response)

**Comment by timfoulkes** [comment]
> Can you give me the username of the account? You can email me it if you want at [ericfang1935@gmail.com](mailto:ericfang1935@gmail.com)

Okay so when I tried adding several accounts yesterday afternoon and got that same error message each time, but when I tried again in the evening it added them fine, but trying again now I'm getting that same error message again? Also the post isn't posting from the Instagram feeds I did add (the Twitter feeds are working fine tho).

**Comment by ericf1** [comment]
It should work now-- I put a temporary solution by requesting less, but I will look into trying to have a permanent one soon. Thank you all for contributing and helping me.
