### ISSUE TITLE
Bot not able to find / add verified accounts.

### ISSUE THREAD

**Issue by DesperatePea** [ericf1/ftwbot#6]
I have tried adding 2 accounts, that should be public. They are also verified accounts. The bot claims it cannot find the accounts, despite writing the correct usernames.

**Comment by ericf1** [comment]
What is the username of the account?

**Comment by DesperatePea** [comment]
https://www.instagram.com/alcestofficial/
https://www.instagram.com/neigealcest/

Here are the two i had trouble with.
Also it seems i cant test further because both invite links are full.

**Comment by ericf1** [comment]
It should work now. I have changed the API slightly so that we don't get rate limited
